### ISSUE TITLE
Re-assign owner of props after player disconnect and reconnect

### ISSUE THREAD

**Issue by ghost** [storm37000/PatchProtect#1]
Currently, PatchProtect assigns any owned props to "Disconnected" if a player disconnects, however when they reconnect, the owner is not restored and thus if they reconnect before their props are cleaned up, they are unable to access the props they could prior. This makes it awkward if players need to reconnect to mount content, or if their game crashes, as all of their builds will be inaccessible to them.
A possible solution is to retain the owner and mark them for automatic deletion some other way, or perhaps store the owner of the props and restore it when they reconnect? Not sure about the practicality of this with high prop counts, though.

**Comment by Synkstar** [comment]
#2 Fixed it...
